exclude = [
    "tests"
]

[lint]
extend-select = [
    "UP",   # pyupgrade
    "D",    # pydocstyle
    "B",    # flake8-bugbear
    "SIM",  # flake8-simplify
    "I",    # isort
    "TCH",  # type checking
    "ANN",  # annotations
    "DOC",  # docstrings
]

ignore = [
    "ANN101",  # Missing type annotation for self in method
    "ANN102",  # Missing type annotation for cls in classmethod
    "ANN204",  # Missing return type annotation in __init__ method
    "ANN401",  # we are using Any in kwargs, so ignore those
    "UP007",   # Imho a: Optional[int] = None is more readable than a: (int | None) = None for kwargs

    "D203",    # 1 blank line required before class docstring (we use D211)
    "D213",    # Multi-line docstring summary should start at the second line - we use D212 (starting on the same line)
    "D404",    # First word of the docstring should not be This
]

[lint.flake8-annotations]
mypy-init-return = true
